# Generated by Django 5.0.7 on 2024-07-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_curso', models.CharField(max_length=10)),
                ('Descricao', models.CharField(max_length=100)),
                ('Nivel', models.CharField(choices=[('B', 'BASICO'), ('I', 'INTERMEDIARIO'), ('A', 'AVANCADO')], default='B', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Estudantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=50)),
                ('CPF', models.CharField(max_length=11)),
                ('Data_Nascimento', models.DateTimeField()),
                ('Celular', models.CharField(max_length=14)),
            ],
        ),
    ]
