# Generated by Django 5.0.7 on 2024-07-24 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Perdiodo', models.CharField(choices=[('M', 'MATUTINO'), ('V', 'VESPERTINO'), ('N', 'NOTURNO')], default='M', max_length=1)),
                ('id_curs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.curso')),
                ('id_estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.estudantes')),
            ],
        ),
    ]
